apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.12.2
      helm:
        valueFiles:
          - $myrepo/charts/cert-manager/values.yaml
    - repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
      targetRevision: main
      ref: myrepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
