apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-job
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
    path: charts/flink-jobs
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
