apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: 'https://github.com/apache/flink-kubernetes-operator.git'
    targetRevision: 1.5.0
    path: helm/flink-kubernetes-operator
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/apache/flink-kubernetes-operator
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '-50'
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
    path: charts/flink
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
