apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/apache/flink-kubernetes-operator.git'
    targetRevision: HEAD
    path: helm/flink-kubernetes-operator
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/apache/flink-kubernetes-operator
  destination:
    namespace: default
    server: https://kubernetes.default.svc
