apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/minio/minio
    path: helm/minio
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicas
          value: "1"
        - name: resources.requests.memory
          value: 512Mi
        - name: mode
          value: standalone
        - name: persistence.enabled
          value: "false"
        - name: rootUser
          value: rootuser
        - name: rootPassword
          value: rootpass123
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
