apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: default
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/minio/minio'
      path: helm/minio
      targetRevision: master
      helm:
        valueFiles:
          - $myrepo/charts/minio/values.yaml
    - repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
      targetRevision: main
      ref: myrepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
