apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: default
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: postgresql
      targetRevision: 12.6.0
      helm:
        valueFiles:
          - $myrepo/charts/postgres/values.yaml
    - repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
      targetRevision: main
      ref: myrepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
