apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: '-100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
      targetRevision: main
      ref: myRepo
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: 47.1.0
      helm:
        valueFiles:
          - $myRepo/charts/prometheus/values.yaml      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
