apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: prometheus
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 47.1.0
    helm:
      values: |-
        prometheus-node-exporter:
          hostRootFsMount:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            failurePolicy: Ignore
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
