apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: default
spec:
  project: default
  sources:
    - repoURL: 'https://charts.redpanda.com'
      chart: redpanda
      targetRevision: 4.0.52
      helm:
        valueFiles:
          - $myrepo/charts/redpanda/values.yaml
    - repoURL: 'https://github.com/ppawelzak/k8s-streaming-platform.git'
      targetRevision: main
      ref: myrepo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
